services:
  postgresql:
    image: bitnami/postgresql:15
    container_name: postgresql-container
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql  # Persist PostgreSQL data
    networks:
      - postgresql_network

volumes:
  postgresql_data:
    driver: local

networks:
  postgresql_network:
    driver: bridge
